name: Test CI
run-name: ${{ github.actor }} is Test CI 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Test with Gradle
          run: ./gradlew clean test
        - name: Build with Gradle
          run: ./gradlew clean build -x test